spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce
spring.datasource.username=postgres
spring.datasource.password=leo
spring.datasource.driver-class-name=org.postgresql.Driver
